DROP SEQUENCE BOARDSEQ;
DROP TABLE BOARD;

CREATE SEQUENCE BOARDSEQ;
CREATE TABLE BOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTEXT VARCHAR2(2000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'관리자','SPRING TEST','TEST입니다.',SYSDATE);

SELECT * FROM BOARD;